### PR TITLE
Feature/preserve octave of sounds

### PR DESCRIPTION
**Pull request by JakubBilski**
I added "octave" getter in base_sound. Nothing should break because of that (base_sound.note results did not change). Now, when we have it, we probably want to use this octave info in chords generation.

Example ("Jedzie pociąg"):
Before
image

Now
image

(The 7th note in the second row is now ok)

### CODE REVIEW

**Review by JakubBrojacz — APPROVED** [review]

**Comment by AnnaMBuchman** [comment]
Nie działa! nie mergować!
płonie ognisko w c-moll, który ma dźwięki poniżej c 4 sypie błędem przy poście

**Comment by AnnaMBuchman** [comment]
obraz

**Comment by JakubBilski** [comment]
This error was fixed in other branch and will be merged soon

**Comment by AnnaMBuchman** [comment]
obraz

**Pull request merged**
